from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.gov_support import GovSupportProgram, ApplicationKit
from app.utils.slug import make_slug
from app.utils.markdown import render_markdown
from datetime import date

GOV_PROGRAMS = [
    {
        "title": "2026년 예비창업패키지",
        "organization": "중소벤처기업부",
        "description": "혁신적인 기술 아이디어를 보유한 예비창업자의 창업 사업화를 지원합니다. 사업계획서 평가를 통해 선발하며, 시제품 제작, 마케팅, 지식재산권 취득 등에 사업화 자금을 활용할 수 있습니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어,제조,바이오",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "최대 1억원",
        "deadline": date(2026, 4, 15),
        "start_date": date(2026, 3, 1),
        "status": "모집중",
        "keywords": "예비창업,사업화,자금,시제품",
    },
    {
        "title": "초기창업패키지 2026",
        "organization": "중소벤처기업부",
        "description": "창업 3년 이내 초기 스타트업을 대상으로 사업화 자금과 전담 멘토링을 지원합니다. 기술 기반 혁신 아이디어로 성장 잠재력이 높은 기업을 선발합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어,바이오,헬스케어",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 1억원",
        "deadline": date(2026, 5, 10),
        "start_date": date(2026, 3, 15),
        "status": "모집중",
        "keywords": "초기창업,사업화,멘토링,자금",
    },
    {
        "title": "창업성장기술개발사업 (디딤돌)",
        "organization": "중소벤처기업부",
        "description": "중소기업의 기술개발 및 사업화를 위한 R&D 자금을 지원합니다. 기술 혁신형 창업기업의 성장을 촉진하며, 기술개발 성공 시 사업화 연계 지원도 가능합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어,제조,하드웨어,바이오",
        "business_stage": "성장기",
        "business_size": "소기업",
        "funding_amount": "최대 3억원",
        "deadline": date(2026, 3, 31),
        "start_date": date(2026, 2, 1),
        "status": "모집중",
        "keywords": "R&D,기술개발,디딤돌,사업화",
    },
    {
        "title": "서울 청년창업사관학교",
        "organization": "서울산업진흥원(SBA)",
        "description": "서울 소재 만 39세 이하 청년 예비창업자를 대상으로 창업 공간, 교육, 멘토링, 사업화 자금을 패키지로 지원합니다. 입주 기간 동안 집중 육성 프로그램을 운영합니다.",
        "support_type": "자금",
        "region": "서울",
        "industry": "IT,소프트웨어,콘텐츠,미디어",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "최대 5천만원",
        "deadline": date(2026, 4, 30),
        "start_date": date(2026, 3, 1),
        "status": "모집중",
        "keywords": "청년,서울,창업사관학교,사업화,공간",
    },
    {
        "title": "경기도 스타트업 엑셀러레이팅",
        "organization": "경기창조경제혁신센터",
        "description": "경기도 소재 스타트업을 대상으로 엑셀러레이팅 프로그램을 운영합니다. 데모데이, 투자 연계, 해외 진출 지원 등 성장 단계별 맞춤 프로그램을 제공합니다.",
        "support_type": "멘토링",
        "region": "경기",
        "industry": "IT,소프트웨어,제조",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "프로그램 참가비 무료",
        "deadline": date(2026, 5, 31),
        "start_date": date(2026, 4, 1),
        "status": "모집중",
        "keywords": "엑셀러레이팅,데모데이,투자,멘토링",
    },
    {
        "title": "K-Startup 글로벌 챌린지",
        "organization": "중소벤처기업부",
        "description": "해외 진출을 목표로 하는 스타트업을 위한 글로벌 엑셀러레이팅 프로그램입니다. 현지 멘토링, 사무공간, 데모데이 기회를 제공하며 실리콘밸리, 싱가포르 등에서 운영됩니다.",
        "support_type": "멘토링",
        "region": "전국",
        "industry": "IT,소프트웨어,바이오",
        "business_stage": "성장기",
        "business_size": "소기업",
        "funding_amount": "활동비 지원",
        "deadline": date(2026, 6, 15),
        "start_date": date(2026, 5, 1),
        "status": "모집중",
        "keywords": "글로벌,해외진출,실리콘밸리,엑셀러레이팅",
    },
    {
        "title": "부산 스타트업 캠프",
        "organization": "부산창조경제혁신센터",
        "description": "부산 지역 예비창업자 및 초기 스타트업을 위한 집중 교육 프로그램입니다. 비즈니스 모델 수립, 린스타트업 방법론, 피칭 교육 등을 제공합니다.",
        "support_type": "교육",
        "region": "부산",
        "industry": "IT,소프트웨어,콘텐츠,미디어,유통",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "교육비 무료",
        "deadline": date(2026, 4, 20),
        "start_date": date(2026, 3, 10),
        "status": "모집중",
        "keywords": "교육,부산,린스타트업,비즈니스모델,피칭",
    },
    {
        "title": "창업보육센터 입주기업 모집",
        "organization": "한국창업보육협회",
        "description": "전국 대학 및 공공 창업보육센터 입주기업을 모집합니다. 사무공간, 회의실, 네트워킹 등 인프라를 제공하며, 입주 기간은 최대 3년입니다.",
        "support_type": "공간",
        "region": "전국",
        "industry": "IT,소프트웨어,제조,바이오,콘텐츠",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "임대료 감면",
        "deadline": None,
        "status": "상시",
        "keywords": "창업보육,사무공간,입주,인프라",
    },
    {
        "title": "소셜벤처 육성사업",
        "organization": "고용노동부",
        "description": "사회적 가치 창출과 영리 활동을 병행하는 소셜벤처를 지원합니다. 사업화 자금, 멘토링, 판로 지원, 임팩트 투자 연계 등을 제공합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "ESG,소셜벤처",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 7천만원",
        "deadline": date(2026, 5, 15),
        "start_date": date(2026, 4, 1),
        "status": "모집중",
        "keywords": "소셜벤처,사회적가치,임팩트,ESG",
    },
    {
        "title": "여성창업경진대회",
        "organization": "여성기업종합지원센터",
        "description": "혁신적인 아이디어를 가진 여성 (예비)창업자를 발굴·육성하기 위한 경진대회입니다. 수상자에게는 사업화 자금, 멘토링, 네트워킹 기회가 제공됩니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어,콘텐츠,미디어,유통,커머스",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "최대 3천만원",
        "deadline": date(2026, 6, 30),
        "start_date": date(2026, 5, 1),
        "status": "모집중",
        "keywords": "여성창업,경진대회,사업화,네트워킹",
    },
    {
        "title": "대전 AI 스타트업 지원사업",
        "organization": "대전정보문화산업진흥원",
        "description": "AI/빅데이터 기반 스타트업을 위한 특화 지원사업입니다. GPU 서버 이용, AI 전문 멘토링, 데이터 활용 지원, 사업화 자금을 패키지로 제공합니다.",
        "support_type": "자금",
        "region": "대전",
        "industry": "IT,소프트웨어",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 8천만원",
        "deadline": date(2026, 4, 10),
        "start_date": date(2026, 3, 1),
        "status": "모집중",
        "keywords": "AI,빅데이터,GPU,사업화,대전",
    },
    {
        "title": "중소기업 수출바우처",
        "organization": "중소벤처기업부",
        "description": "수출 역량이 있는 중소기업에 해외 마케팅, 통·번역, 물류, 법률 등 수출 관련 서비스 이용 바우처를 지원합니다.",
        "support_type": "컨설팅",
        "region": "전국",
        "industry": "제조,하드웨어,IT,소프트웨어",
        "business_stage": "성장기",
        "business_size": "중소기업",
        "funding_amount": "최대 1억원",
        "deadline": date(2026, 3, 20),
        "start_date": date(2026, 2, 1),
        "status": "모집중",
        "keywords": "수출,해외마케팅,바우처,물류",
    },
    {
        "title": "창업도약패키지 2026",
        "organization": "중소벤처기업부",
        "description": "3~7년차 도약기 스타트업의 재도전과 성장을 지원합니다. 사업 모델 고도화, 해외 진출, 투자 유치 연계 등 성장 단계에 맞는 맞춤형 지원을 제공합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어,제조,바이오",
        "business_stage": "도약기",
        "business_size": "소기업",
        "funding_amount": "최대 3억원",
        "deadline": date(2026, 5, 20),
        "start_date": date(2026, 4, 1),
        "status": "모집중",
        "keywords": "도약,성장,재도전,투자유치,해외진출",
    },
    {
        "title": "ICT 이노베이션 스퀘어",
        "organization": "과학기술정보통신부",
        "description": "ICT 분야 인재 양성 및 창업 지원 프로그램입니다. AI, 클라우드, IoT 등 신기술 교육과 함께 창업 보육 및 공간을 제공합니다.",
        "support_type": "교육",
        "region": "서울",
        "industry": "IT,소프트웨어",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "교육비 무료",
        "deadline": None,
        "status": "상시",
        "keywords": "ICT,AI,클라우드,IoT,교육,인재양성",
    },
    {
        "title": "광주 AI 집적단지 입주 지원",
        "organization": "광주광역시",
        "description": "광주 AI 집적단지에 입주할 AI 스타트업을 모집합니다. 사무공간, GPU 클러스터, 데이터 센터 이용 등 AI 개발에 필요한 인프라를 무상 제공합니다.",
        "support_type": "공간",
        "region": "광주",
        "industry": "IT,소프트웨어",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "공간 무상 제공",
        "deadline": date(2026, 7, 31),
        "start_date": date(2026, 6, 1),
        "status": "모집중",
        "keywords": "AI,광주,집적단지,GPU,공간",
    },
    {
        "title": "인천 스타트업 파크",
        "organization": "인천테크노파크",
        "description": "인천 지역 스타트업을 위한 종합 지원 프로그램입니다. 사무공간 제공, 시제품 제작 지원, 멘토링, 데모데이 등을 패키지로 운영합니다.",
        "support_type": "공간",
        "region": "인천",
        "industry": "IT,소프트웨어,제조,하드웨어",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "공간+시제품 지원",
        "deadline": date(2026, 5, 1),
        "start_date": date(2026, 4, 1),
        "status": "모집중",
        "keywords": "인천,공간,시제품,스타트업파크",
    },
    {
        "title": "바이오 스타트업 육성 프로그램",
        "organization": "한국바이오협회",
        "description": "바이오·헬스케어 분야 스타트업을 대상으로 전문 멘토링, 규제 컨설팅, 임상 지원, 투자 연계를 제공하는 특화 프로그램입니다.",
        "support_type": "멘토링",
        "region": "전국",
        "industry": "바이오,헬스케어",
        "business_stage": "성장기",
        "business_size": "소기업",
        "funding_amount": "프로그램비 무료",
        "deadline": date(2026, 4, 25),
        "start_date": date(2026, 3, 15),
        "status": "모집중",
        "keywords": "바이오,헬스케어,임상,규제,투자연계",
    },
    {
        "title": "콘텐츠 스타트업 창업 지원",
        "organization": "한국콘텐츠진흥원",
        "description": "콘텐츠(게임, 영상, 음악, 웹툰 등) 분야 창업자를 위한 사업화 지원 프로그램입니다. 제작비, 마케팅, IP 컨설팅을 지원합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "콘텐츠,미디어",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 5천만원",
        "deadline": date(2026, 5, 5),
        "start_date": date(2026, 4, 1),
        "status": "모집중",
        "keywords": "콘텐츠,게임,영상,웹툰,IP,제작비",
    },
    {
        "title": "스마트 제조 혁신 지원",
        "organization": "스마트제조혁신추진단",
        "description": "제조 스타트업의 스마트 팩토리 구축을 지원합니다. IoT, AI 기반 생산 자동화, 품질 관리 시스템 도입 비용의 50%를 보조합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "제조,하드웨어",
        "business_stage": "성장기",
        "business_size": "중소기업",
        "funding_amount": "최대 2억원 (50% 보조)",
        "deadline": date(2026, 6, 30),
        "start_date": date(2026, 5, 1),
        "status": "모집중",
        "keywords": "스마트팩토리,제조,IoT,자동화,품질관리",
    },
    {
        "title": "경기도 1인 창조기업 지원",
        "organization": "경기도경제과학진흥원",
        "description": "경기도 소재 1인 창조기업(프리랜서, 솔로 창업자)을 위한 사무공간, 세무·법률 컨설팅, 네트워킹 기회를 제공합니다.",
        "support_type": "공간",
        "region": "경기",
        "industry": "IT,소프트웨어,콘텐츠,미디어",
        "business_stage": "초기",
        "business_size": "1인",
        "funding_amount": "공간 무상 제공",
        "deadline": None,
        "status": "상시",
        "keywords": "1인창조기업,경기도,공간,컨설팅",
    },
    {
        "title": "TIPS (민간투자주도형 기술창업지원)",
        "organization": "중소벤처기업부",
        "description": "엔젤투자자 및 VC로부터 투자를 유치한 기술 기반 스타트업에 R&D 자금과 사업화 자금을 매칭 지원합니다. 최대 5억원 규모의 종합 지원입니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어,바이오,제조",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 5억원",
        "deadline": date(2026, 12, 31),
        "status": "상시",
        "keywords": "TIPS,투자,R&D,기술창업,엔젤",
    },
    {
        "title": "대구 디지털 혁신 창업지원",
        "organization": "대구디지털혁신진흥원",
        "description": "대구 지역 디지털 분야(AI, 블록체인, 메타버스 등) 예비창업자 및 초기 스타트업을 대상으로 교육, 멘토링, 사업화 자금을 지원합니다.",
        "support_type": "자금",
        "region": "대구",
        "industry": "IT,소프트웨어",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "최대 4천만원",
        "deadline": date(2026, 4, 15),
        "start_date": date(2026, 3, 1),
        "status": "모집중",
        "keywords": "대구,디지털,AI,블록체인,메타버스",
    },
    {
        "title": "중소기업 특허전략 컨설팅",
        "organization": "특허청",
        "description": "중소기업과 스타트업을 위한 특허 전략 수립, IP 포트폴리오 구축, 특허 분쟁 대응 등 지식재산 전문 컨설팅을 무료로 제공합니다.",
        "support_type": "컨설팅",
        "region": "전국",
        "industry": "IT,소프트웨어,제조,바이오",
        "business_stage": "성장기",
        "business_size": "소기업",
        "funding_amount": "컨설팅 무료",
        "deadline": None,
        "status": "상시",
        "keywords": "특허,IP,지식재산,컨설팅",
    },
    {
        "title": "청년 디지털 일자리 사업",
        "organization": "고용노동부",
        "description": "IT·디지털 분야 중소기업이 만 15~34세 청년을 채용할 경우 인건비의 일부를 지원합니다. 스타트업 인력 확보에 도움이 됩니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "IT,소프트웨어",
        "business_stage": "성장기",
        "business_size": "소기업",
        "funding_amount": "월 최대 190만원/인",
        "deadline": date(2026, 12, 31),
        "status": "상시",
        "keywords": "청년,일자리,인건비,채용,디지털",
    },
    {
        "title": "그린 스타트업 지원사업",
        "organization": "환경부",
        "description": "환경·에너지·기후변화 분야 스타트업을 위한 사업화 지원 프로그램입니다. 친환경 기술개발, ESG 컨설팅, 탄소배출권 관련 지원을 제공합니다.",
        "support_type": "자금",
        "region": "전국",
        "industry": "ESG,소셜벤처",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 1억원",
        "deadline": date(2026, 5, 30),
        "start_date": date(2026, 4, 1),
        "status": "모집중",
        "keywords": "그린,환경,ESG,기후변화,탄소",
    },
    {
        "title": "판교 스타트업 캠퍼스 입주",
        "organization": "경기도",
        "description": "판교 테크노밸리 스타트업 캠퍼스에 입주할 기업을 모집합니다. 사무공간, 회의실, 라운지 등 업무 인프라와 함께 투자자 네트워킹 기회를 제공합니다.",
        "support_type": "공간",
        "region": "경기",
        "industry": "IT,소프트웨어",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "임대료 50% 감면",
        "deadline": date(2026, 3, 31),
        "start_date": date(2026, 3, 1),
        "status": "모집중",
        "keywords": "판교,공간,입주,테크노밸리,네트워킹",
    },
    {
        "title": "서울 소셜 임팩트 챌린지",
        "organization": "서울시사회적경제지원센터",
        "description": "사회적 문제 해결을 목표로 하는 소셜벤처 및 사회적기업을 위한 지원사업입니다. 사업화 자금, 임팩트 측정 컨설팅, 판로 개척을 지원합니다.",
        "support_type": "자금",
        "region": "서울",
        "industry": "ESG,소셜벤처",
        "business_stage": "초기",
        "business_size": "소기업",
        "funding_amount": "최대 5천만원",
        "deadline": date(2026, 4, 20),
        "start_date": date(2026, 3, 15),
        "status": "모집중",
        "keywords": "소셜임팩트,사회적기업,서울,판로",
    },
    {
        "title": "K-유니콘 프로젝트",
        "organization": "중소벤처기업부",
        "description": "글로벌 유니콘 기업 육성을 위한 스케일업 지원사업입니다. 해외 진출, 대규모 투자 유치, M&A 전략 수립 등 성장 가속화를 지원합니다.",
        "support_type": "멘토링",
        "region": "전국",
        "industry": "IT,소프트웨어,바이오",
        "business_stage": "도약기",
        "business_size": "중소기업",
        "funding_amount": "맞춤형 지원",
        "deadline": date(2026, 6, 30),
        "start_date": date(2026, 5, 1),
        "status": "모집중",
        "keywords": "유니콘,스케일업,글로벌,투자유치,M&A",
    },
    {
        "title": "부산 e-커머스 창업지원",
        "organization": "부산경제진흥원",
        "description": "부산 지역 e-커머스·온라인 유통 분야 창업자를 위한 지원사업입니다. 쇼핑몰 구축, 마케팅, 물류 교육과 사업화 자금을 지원합니다.",
        "support_type": "자금",
        "region": "부산",
        "industry": "유통,커머스",
        "business_stage": "예비창업",
        "business_size": "1인",
        "funding_amount": "최대 3천만원",
        "deadline": date(2026, 4, 30),
        "start_date": date(2026, 3, 15),
        "status": "모집중",
        "keywords": "e커머스,온라인유통,부산,쇼핑몰,마케팅",
    },
]

SAMPLE_KITS = {
    "2026년 예비창업패키지": {
        "checklist_md": """- 사업자등록증 (미등록 시 사업계획서로 대체 가능)
- 사업계획서 (중기부 양식)
- 기술 관련 증빙 자료 (특허, 논문, 수상 등)
- 팀 구성원 이력서
- 시장분석 보고서
- 재무계획서 (3개년)""",
        "guide_md": """## 예비창업패키지 신청 가이드

### 1단계: 자격 요건 확인
- 만 39세 이하 예비창업자
- 사업자등록 이전 또는 등록 후 1년 미만
- 기술 기반 혁신 아이디어 보유

### 2단계: 사업계획서 작성
- 중기부 공식 양식 활용
- 기술 혁신성, 시장성, 성장 가능성 중심으로 작성
- 구체적인 사업화 계획과 자금 사용 계획 포함

### 3단계: 온라인 접수
- K-Startup 홈페이지에서 온라인 접수
- 첨부 서류 업로드

### 꿀팁
- 발표 평가가 핵심이므로 피칭 연습 필수
- 시제품이 있으면 가산점
- 팀 구성이 탄탄할수록 유리""",
    }
}


async def seed_gov_data(session: AsyncSession):
    result = await session.execute(select(GovSupportProgram).limit(1))
    if result.scalar_one_or_none():
        return

    for prog_data in GOV_PROGRAMS:
        slug = make_slug(prog_data["title"])
        program = GovSupportProgram(slug=slug, **prog_data)
        session.add(program)

    await session.flush()

    for title, kit_data in SAMPLE_KITS.items():
        program = (await session.execute(
            select(GovSupportProgram).where(GovSupportProgram.title == title)
        )).scalar_one_or_none()
        if program:
            kit = ApplicationKit(
                program_id=program.id,
                checklist_md=kit_data["checklist_md"],
                checklist_html=render_markdown(kit_data["checklist_md"]),
                guide_md=kit_data["guide_md"],
                guide_html=render_markdown(kit_data["guide_md"]),
            )
            session.add(kit)

    await session.commit()
